In [10]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [11]:
df=pd.read_csv('final_data.csv')

In [12]:
df.to_string()

'     Order_ID  Distance_km Weather Traffic_Level Time_of_Day Vehicle_Type  Preparation_Time_min  Courier_Experience_yrs  Delivery_Time_min\n0         522         7.93   Windy           Low   Afternoon      Scooter                    12                     1.0                 43\n1         738        16.42   Clear        Medium     Evening         Bike                    20                     2.0                 84\n2         741         9.52   Foggy           Low       Night      Scooter                    28                     1.0                 59\n3         661         7.44   Rainy        Medium   Afternoon      Scooter                     5                     1.0                 37\n4         412        19.03   Clear           Low     Morning         Bike                    16                     5.0                 68\n5         679        19.40   Clear           Low     Evening      Scooter                     8                     9.0                 57\n6         514        17.39   Clear        Medium     Evening      Scooter                     5                     6.0                 46\n7         860         1.78   Snowy           Low     Evening          Car                    20                     6.0                 35\n8         137        10.62   Foggy           Low     Evening      Scooter                    29                     1.0                 73\n9         812        16.86   Snowy        Medium   Afternoon          Car                    13                     4.0                 88\n10         77        15.54   Clear           Low       Night         Bike                    29                     1.0                 76\n11        637        10.89   Clear          High       Night         Bike                    12                     5.0                 53\n12        974         4.69   Rainy        Medium     Evening      Scooter                    12                     7.0                 36\n13        900         2.17   Snowy           Low     Evening          Car                    15                     3.0                 35\n14        281        17.86   Rainy           Low   Afternoon         Bike                     5                     1.0                 50\n15        884         2.53   Snowy           Low     Morning         Bike                     6                     8.0                 24\n16        762         6.58   Foggy           Low     Evening          Car                     6                     7.0                 27\n17        320         5.38   Clear        Medium     Evening      Scooter                    26                     1.0                 47\n18        550        15.56   Rainy           Low   Afternoon      Scooter                    28                     0.0                 72\n19        175        13.08   Rainy           Low     Morning          Car                    16                     4.0                 58\n20        372         0.86   Clear          High   Afternoon         Bike                    26                     5.0                 37\n21        528         5.83   Clear          High     Evening          Car                    27                     9.0                 56\n22        236        14.59   Clear        Medium     Morning         Bike                    15                     6.0                 64\n23        102        12.91   Windy        Medium     Evening         Bike                    11                     6.0                 56\n24        987        13.92   Snowy           Low     Morning      Scooter                    18                     4.0                 70\n25        903         4.04   Snowy           Low       Night         Bike                    11                     9.0                 70\n26        948        18.05   Clear        Medium     Evening      Scooter                    10                     7.0                123\n27        347        12.88   Clear        Medium     Morning      Scooter                     8                     5.0                 52\n28        140        19.45   Rainy          High     Morning      Scooter                    20                     6.0                108\n29        622         4.58   Clear          High     Morning      Scooter                    22                     9.0                 45\n30        500        19.73   Foggy        Medium     Evening         Bike                    27                     4.0                111\n31        371         2.47   Windy        Medium     Morning         Bike                    27                     2.0                 44\n32        199        17.80   Snowy        Medium     Morning         Bike                    16                     9.0                 73\n33        688         5.96   Clear        Medium   Afternoon         Bike                    22                     7.0                 45\n34        585        12.85   Windy        Medium   Afternoon      Scooter                    18                     7.0                 61\n35        902         1.02   Clear        Medium   Afternoon         Bike                    25                     4.0                 34\n36         60         6.84   Rainy        Medium       Night          Car                    14                     8.0                 47\n37        329         8.68   Rainy        Medium     Morning         Bike                     8                     5.0                 52\n38         97        10.69   Clear        Medium       Night         Bike                    25                     9.0                 67\n39        975         1.11   Clear           Low     Morning         Bike                     5                     6.0                  8\n40        300         2.16   Snowy           Low     Evening      Scooter                    15                     0.0                 36\n41        278        13.17   Windy        Medium   Afternoon         Bike                    16                     4.0                 67\n42        925         8.79   Snowy           Low       Night         Bike                    14                     6.0                 43\n43        602         5.93   Clear           Low   Afternoon      Scooter                    19                     3.0                 36\n44        440         2.09   Rainy           Low       Night         Bike                    23                     2.0                 36\n45        838         7.57   Clear           Low     Morning         Bike                    21                     0.0                 56\n46        571        10.52   Rainy        Medium   Afternoon      Scooter                     8                     4.0                 56\n47        880         4.83   Rainy           Low     Morning          Car                    25                     9.0                 47\n48        262        19.81   Snowy        Medium   Afternoon          Car                    20                     5.0                104\n49        579        10.10   Rainy           Low     Evening          Car                     8                     4.0                 50\n50         24         7.64   Windy           Low   Afternoon          Car                    10                     8.0                 31\n51         31        12.35   Clear           Low     Morning      Scooter                    10                     6.0                 35\n52        618         5.90   Rainy           Low     Evening          Car                    26                     9.0                 44\n53         11         0.90   Clear           Low   Afternoon         Bike                    20                     8.0                 23\n54        222        11.58   Clear        Medium     Morning      Scooter                    16                     2.0                 61\n55        821        16.16   Clear          High   Afternoon         Bike                    11                     1.0                 82\n56        297        15.51   Clear           Low     Evening         Bike                    17                     9.0                 69\n57         55        12.16   Windy          High     Evening      Scooter                    11                     0.0                 69\n58        543         4.96   Rainy          High     Morning         Bike                    21                     0.0                 60\n59        210         3.64   Windy          High     Evening         Bike                    17                     6.0                 40\n60        605         2.85   Clear           Low     Morning      Scooter                    26                     0.0                 38\n61        693        10.40   Clear           Low     Evening         Bike                    16                     4.0                 52\n62        663        12.31   Windy           Low     Morning         Bike                    29                     4.0                 68\n63        867         3.53   Clear        Medium   Afternoon         Bike                    13                     7.0                 31\n64         71        15.56   Clear        Medium     Evening         Bike                    14                     3.0                 54\n65        544        13.60   Clear        Medium   Afternoon         Bike                    27                     0.0                 87\n66        108        15.23   Snowy          High     Morning         Bike                     5                     0.0                 62\n67        591         3.21   Rainy          High       Night      Scooter                    16                     0.0                 42\n68        742         6.38   Snowy           Low     Evening         Bike                    16                     1.0                111\n69        293        16.54   Rainy           Low   Afternoon      Scooter                     6                     7.0                 51\n70        290        12.02   Clear           Low     Morning          Car                     9                     7.0                 41\n71        653        11.94   Clear           Low     Evening         Bike                    20                     3.0                 69\n72         40         9.08   Clear           Low   Afternoon      Scooter                    14                     5.0                 49\n73        590         3.46   Snowy        Medium     Morning      Scooter                    23                     3.0                 48\n74        308         6.80   Foggy        Medium     Morning      Scooter                    13                     7.0                 46\n75        680        17.38   Rainy        Medium   Afternoon      Scooter                    11                     2.0                 92\n76         67         3.25   Clear           Low     Morning         Bike                    23                     7.0                 32\n77        276        10.28   Clear        Medium     Evening      Scooter                    29                     3.0                 71\n78         68        16.14   Clear           Low       Night          Car                     6                     9.0                 65\n79        319         3.55   Clear        Medium     Evening         Bike                    23                     0.0                 43\n80        999        19.03   Clear           Low   Afternoon          Car                    26                     5.0                 68\n81        715         7.30   Clear           Low       Night      Scooter                    14                     7.0                 28\n82        754         7.03   Clear           Low     Evening      Scooter                    21                     1.0                 44\n83        328        12.43   Snowy           Low   Afternoon          Car                    12                     0.0                 70\n84        452        11.39   Rainy          High     Evening      Scooter                    14                     1.0                 72\n85        523        19.41   Clear           Low     Morning          Car                     7                     3.0                 48\n86        219        13.17   Rainy          High     Evening      Scooter                    17                     8.0                 69\n87        788         8.32   Rainy           Low   Afternoon          Car                    12                     2.0                 49\n88        765         1.15   Clear           Low   Afternoon      Scooter                    26                     4.0                 30\n89         89        17.80   Windy          High   Afternoon          Car                    12                     9.0                 73\n90         64         7.46   Clear        Medium     Evening         Bike                     8                     5.0                 42\n91        827         7.25   Clear        Medium   Afternoon      Scooter                    18                     4.0                 45\n92        717        16.70   Clear        Medium   Afternoon      Scooter                    28                     1.0                 76\n93        352        17.20   Rainy          High   Afternoon      Scooter                    14                     2.0                 94\n94        937         0.86   Clear        Medium   Afternoon          Car                    21                     7.0                 28\n95        257        18.76   Clear        Medium     Evening          Car                    15                     2.0                 80\n96        636         9.22   Clear        Medium   Afternoon          Car                    18                     9.0                 57\n97        645         2.84   Clear           Low     Evening      Scooter                    24                     2.0                 35\n98        555        17.59   Clear           Low     Morning         Bike                    24                     6.0                 69\n99        960        14.89   Snowy          High     Morning      Scooter                    17                     6.0                 87\n100       169         1.30   Clear        Medium     Evening         Bike                    22                     4.0                 31\n101       918        18.99   Rainy          High   Afternoon         Bike                    10                     6.0                 70\n102       824         8.26   Snowy           Low   Afternoon         Bike                    15                     1.0                 57\n103       986        10.16   Clear          High       Night         Bike                    12                     5.0                 52\n104        87        14.73   Rainy           Low   Afternoon         Bike                    24                     6.0                 74\n105       433        12.56   Clear          High     Evening         Bike                    17                     5.0                 69\n106       185         5.53   Clear        Medium   Afternoon         Bike                    19                     1.0                 44\n107       979        10.18   Foggy        Medium     Morning         Bike                    25                     3.0                 73\n108       535        15.50   Clear        Medium     Morning      Scooter                    28                     9.0                 91\n109       893        16.69   Foggy        Medium     Evening      Scooter                     8                     2.0                 65\n110       426        11.22   Windy          High     Evening         Bike                    25                     5.0                 79\n111       714         8.53   Clear           Low     Evening      Scooter                     8                     2.0                 41\n112       261        12.49   Clear        Medium     Morning         Bike                    25                     4.0                 77\n113       238         0.97   Clear           Low       Night      Scooter                    24                     8.0                 26\n114       560        12.60   Windy        Medium   Afternoon          Car                     8                     6.0                 58\n115       584         6.91   Clear        Medium     Evening      Scooter                    28                     9.0                 56\n116       446        18.97   Clear           Low     Evening          Car                    25                     4.0                141\n117       801        14.29   Windy        Medium     Morning         Bike                    14                     7.0                 78\n118       600         1.30   Foggy           Low     Evening         Bike                    19                     5.0                 29\n119       850        12.11   Rainy           Low     Morning         Bike                     9                     5.0                 59\n120       266        14.94   Clear        Medium     Morning         Bike                    11                     0.0                 62\n121       996         2.29   Rainy          High   Afternoon          Car                     8                     8.0                 80\n122       530        17.36   Rainy          High   Afternoon         Bike                    24                     1.0                105\n123        56        18.48   Clear        Medium       Night         Bike                     8                     0.0                 82\n124       121        16.25   Foggy          High     Morning         Bike                    10                     5.0                 91\n125       216         5.13   Clear           Low     Morning          Car                    15                     4.0                 30\n126        73         0.61   Clear           Low   Afternoon      Scooter                    10                     0.0                 16\n127        45         5.55   Foggy          High     Evening         Bike                    18                     1.0                116\n128       722         4.03   Clear        Medium     Evening         Bike                     9                     5.0                 25\n129       282         7.09   Snowy           Low     Morning      Scooter                    13                     8.0                 37\n130       894         8.25   Clear        Medium   Afternoon         Bike                     7                     9.0                 28\n131       915        11.26   Clear           Low       Night         Bike                     5                     6.0                 49\n132       811        19.70   Rainy           Low     Evening         Bike                    10                     2.0                 60\n133       245         0.80   Snowy          High     Evening         Bike                    14                     9.0                 36\n134       823         7.00   Rainy        Medium     Evening         Bike                    17                     9.0                 49\n135       322        14.43   Clear        Medium     Morning          Car                    14                     4.0                113\n136       644         6.89   Rainy        Medium   Afternoon         Bike                    11                     6.0                 43\n137       159         5.13   Foggy        Medium     Evening          Car                    25                     1.0                 60\n138       978         1.50   Clear           Low   Afternoon         Bike                    10                     1.0                 17\n139       942        11.31   Clear        Medium     Evening         Bike                     7                     0.0                 54\n140       463        15.05   Clear        Medium     Evening          Car                    12                     2.0                 66\n141       310         5.78   Foggy           Low   Afternoon      Scooter                     9                     9.0

In [13]:
df

,Order_ID,Distance_km,Weather,Traffic_Level,Time_of_Day,Vehicle_Type,Preparation_Time_min,Courier_Experience_yrs,Delivery_Time_min
0,522,7.93,Windy,Low,Afternoon,Scooter,12,1.0,43
1,738,16.42,Clear,Medium,Evening,Bike,20,2.0,84
2,741,9.52,Foggy,Low,Night,Scooter,28,1.0,59
3,661,7.44,Rainy,Medium,Afternoon,Scooter,5,1.0,37
4,412,19.03,Clear,Low,Morning,Bike,16,5.0,68
...,...,...,...,...,...,...,...,...,...
878,107,8.50,Clear,High,Evening,Car,13,3.0,54
879,271,16.28,Rainy,Low,Morning,Scooter,8,9.0,71
880,861,15.62,Snowy,High,Evening,Scooter,26,2.0,81
881,436,14.17,Clear,Low,Afternoon,Bike,8,0.0,55
882,103,6.63,Foggy,Low,Night,Scooter,24,3.0,58

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 883 entries, 0 to 882
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Order_ID                883 non-null    int64
 1   Distance_km             883 non-null    float64
 2   Weather                 883 non-null    str
 3   Traffic_Level           883 non-null    str
 4   Time_of_Day             883 non-null    str
 5   Vehicle_Type            883 non-null    str
 6   Preparation_Time_min    883 non-null    int64
 7   Courier_Experience_yrs  883 non-null    float64
 8   Delivery_Time_min       883 non-null    int64
dtypes: float64(2), int64(3), str(4)
memory usage: 80.8 KB

In [15]:
df.columns

Index(['Order_ID', 'Distance_km', 'Weather', 'Traffic_Level', 'Time_of_Day',
       'Vehicle_Type', 'Preparation_Time_min', 'Courier_Experience_yrs',
       'Delivery_Time_min'],
      dtype='str')

In [16]:
X=df.drop(columns=['Delivery_Time_min','Order_ID'])

In [17]:
y=df[['Delivery_Time_min']]

In [18]:
from sklearn.linear_model import LinearRegression
from sklearn.compose import make_column_transformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import make_pipeline

In [19]:
ohe=OneHotEncoder()
ohe.fit(df[['Weather','Traffic_Level','Time_of_Day','Vehicle_Type']])
ct=make_column_transformer((OneHotEncoder(handle_unknown='ignore'),['Weather','Traffic_Level','Time_of_Day','Vehicle_Type']),remainder='passthrough')

model=LinearRegression()
pipe=make_pipeline(ct,model)

In [20]:
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
scores=[]
for i in range(1,101):
    X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.1,random_state=i)
    pipe.fit(X_train,y_train)
    y_pred=pipe.predict(X_test)
    y_pred=pd.DataFrame(data=y_pred,columns=['prediction'])
    result=pd.concat([y_test.reset_index(drop=True),y_pred],axis=1)
    score=r2_score(result['Delivery_Time_min'],result['prediction'])
    scores.append(score)
    print(i,score)

1 0.8710171481982205
2 0.7599986267686356
3 0.8578631393190297
4 0.7866820064735773
5 0.84159550256812
6 0.7649810136883611
7 0.8120317564646999
8 0.7866008338029704
9 0.7627818356444238
10 0.650394908625197
11 0.7550211117394439
12 0.7019444220382636
13 0.7334004238806425
14 0.7742047629159877
15 0.7978972664002094
16 0.8797740171647278
17 0.8195930905260258
18 0.8352576671660443
19 0.8483161569909814
20 0.7663713644096586
21 0.7906436179690225
22 0.7448057932345937
23 0.7781244074478048
24 0.6309527948520544
25 0.8183082511577345
26 0.7518089103432292
27 0.6572999586952388
28 0.8003012677733043
29 0.842494776427221
30 0.8258937925125538
31 0.7022001316948574
32 0.7925242994780467
33 0.7226247278226944
34 0.7378939083426959
35 0.7415539749601449
36 0.7525654102119578
37 0.7179508058993305
38 0.859360490507938
39 0.6899604789515029
40 0.7572927603714285
41 0.856373978094513
42 0.919918675781515
43 0.8198216811189881
44 0.6593308111409422
45 0.7817750533471997
46 0.8185254607438923
47 0.6638881683383342
48 0.7865524138567191
49 0.8645733598460476
50 0.7357406297682487
51 0.8916821854224559
52 0.7186620264353627
53 0.8424328095981666
54 0.7125795048613599
55 0.7764990485571074
56 0.7308245278290284
57 0.6880308879238859
58 0.7467904256367955
59 0.8471810231338611
60 0.7054798748406317
61 0.7963370283050213
62 0.7115555140899947
63 0.7840646028344248
64 0.766621309952064
65 0.7751054348930091
66 0.7656852525256491
67 0.7877946699026476
68 0.8814855023780984
69 0.7773803015969516
70 0.8783852771173122
71 0.7074710021166601
72 0.6566383208648092
73 0.7679511604557995
74 0.8099397499441443
75 0.8117782068274306
76 0.8366891159702361
77 0.6885986622519371
78 0.6924610964588711
79 0.7751291725232362
80 0.8672273729457902
81 0.6241420800326807
82 0.7649720035956643
83 0.7195005397928267
84 0.7900494935614515
85 0.8174709117632534
86 0.905080778027761
87 0.7528678599011203
88 0.7497306790005622
89 0.8046650420951211
90 0.8385303402237463
91 0.7857428584771149
92 0.8258256757802288
93 0.7736061326391542
94 0.8156011417197125
95 0.7735014375163146
96 0.8718803874130523
97 0.7919369229480123
98 0.8526548631008166
99 0.8022884209265874
100 0.6390117004685851

In [21]:
print(max(scores))

0.919918675781515

In [22]:
print(scores[41])

0.919918675781515

In [23]:
df

,Order_ID,Distance_km,Weather,Traffic_Level,Time_of_Day,Vehicle_Type,Preparation_Time_min,Courier_Experience_yrs,Delivery_Time_min
0,522,7.93,Windy,Low,Afternoon,Scooter,12,1.0,43
1,738,16.42,Clear,Medium,Evening,Bike,20,2.0,84
2,741,9.52,Foggy,Low,Night,Scooter,28,1.0,59
3,661,7.44,Rainy,Medium,Afternoon,Scooter,5,1.0,37
4,412,19.03,Clear,Low,Morning,Bike,16,5.0,68
...,...,...,...,...,...,...,...,...,...
878,107,8.50,Clear,High,Evening,Car,13,3.0,54
879,271,16.28,Rainy,Low,Morning,Scooter,8,9.0,71
880,861,15.62,Snowy,High,Evening,Scooter,26,2.0,81
881,436,14.17,Clear,Low,Afternoon,Bike,8,0.0,55
882,103,6.63,Foggy,Low,Night,Scooter,24,3.0,58

In [24]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.1,random_state=41)
pipe.fit(X_train,y_train)
y_pred=pipe.predict(X_test)

In [25]:
import pickle
pickle.dump(pipe,open("pipe.pkl","wb"))

In [26]:
df.columns

Index(['Order_ID', 'Distance_km', 'Weather', 'Traffic_Level', 'Time_of_Day',
       'Vehicle_Type', 'Preparation_Time_min', 'Courier_Experience_yrs',
       'Delivery_Time_min'],
      dtype='str')